In [2]:
import tensorflow as tf
import numpy as np 
from sklearn import datasets 

#### numpy array 构建数据管道

In [11]:
iris = datasets.load_iris()
iris.keys()

dict_keys(['data', 'target', 'target_names', 'DESCR', 'feature_names', 'filename'])

In [13]:
iris['data'][0:5]

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2]])

In [15]:
## numpy to tensorflow 
ds1 = tf.data.Dataset.from_tensor_slices((iris["data"],iris["target"]))
for features,label in ds1.take(5):
    print(features,label)

tf.Tensor([5.1 3.5 1.4 0.2], shape=(4,), dtype=float64) tf.Tensor(0, shape=(), dtype=int64)
tf.Tensor([4.9 3.  1.4 0.2], shape=(4,), dtype=float64) tf.Tensor(0, shape=(), dtype=int64)
tf.Tensor([4.7 3.2 1.3 0.2], shape=(4,), dtype=float64) tf.Tensor(0, shape=(), dtype=int64)
tf.Tensor([4.6 3.1 1.5 0.2], shape=(4,), dtype=float64) tf.Tensor(0, shape=(), dtype=int64)
tf.Tensor([5.  3.6 1.4 0.2], shape=(4,), dtype=float64) tf.Tensor(0, shape=(), dtype=int64)


#### pandas dataframe 构建数据管道 

In [19]:
import pandas as pd 
iris = datasets.load_iris()

In [20]:
iris.feature_names 
dfiris = pd.DataFrame(iris["data"],columns = iris.feature_names)

In [23]:
dfiris.head(3)

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                5.1               3.5                1.4               0.2
1                4.9               3.0                1.4               0.2
2                4.7               3.2                1.3               0.2

In [26]:
dfiris.to_dict("list").keys()   ## to_dict, value to list 

dict_keys(['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)'])

In [27]:
iris["target"]

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [37]:
ds2 = tf.data.Dataset.from_tensor_slices((dfiris.to_dict("list"),iris["target"]))
for features,label in ds2.take(3):
    print(features,label)

{'sepal length (cm)': <tf.Tensor: id=872, shape=(), dtype=float32, numpy=5.1>, 'sepal width (cm)': <tf.Tensor: id=873, shape=(), dtype=float32, numpy=3.5>, 'petal length (cm)': <tf.Tensor: id=870, shape=(), dtype=float32, numpy=1.4>, 'petal width (cm)': <tf.Tensor: id=871, shape=(), dtype=float32, numpy=0.2>} tf.Tensor(0, shape=(), dtype=int64)
{'sepal length (cm)': <tf.Tensor: id=877, shape=(), dtype=float32, numpy=4.9>, 'sepal width (cm)': <tf.Tensor: id=878, shape=(), dtype=float32, numpy=3.0>, 'petal length (cm)': <tf.Tensor: id=875, shape=(), dtype=float32, numpy=1.4>, 'petal width (cm)': <tf.Tensor: id=876, shape=(), dtype=float32, numpy=0.2>} tf.Tensor(0, shape=(), dtype=int64)
{'sepal length (cm)': <tf.Tensor: id=882, shape=(), dtype=float32, numpy=4.7>, 'sepal width (cm)': <tf.Tensor: id=883, shape=(), dtype=float32, numpy=3.2>, 'petal length (cm)': <tf.Tensor: id=880, shape=(), dtype=float32, numpy=1.3>, 'petal width (cm)': <tf.Tensor: id=881, shape=(), dtype=float32, numpy=0

#### 从csv文件构建数据管道

In [192]:
ds4 = tf.data.experimental.make_csv_dataset(
    file_pattern = ["/Users/jun_yu/Documents/yujun_repository/Wide & Deep/wide-and-deep-titan_0512/train.csv",
                    "/Users/jun_yu/Documents/yujun_repository/Wide & Deep/wide-and-deep-titan_0512/eval.csv"],
    batch_size=3, 
    label_name="survived",
    na_value="",
    num_epochs=1,
    ignore_errors=True)

for data,label in ds4.take(2):
    print(data, label)

OrderedDict([('sex', <tf.Tensor: id=8728, shape=(3,), dtype=string, numpy=array([b'male', b'male', b'female'], dtype=object)>), ('age', <tf.Tensor: id=8720, shape=(3,), dtype=float32, numpy=array([28.  ,  0.92, 36.  ], dtype=float32)>), ('n_siblings_spouses', <tf.Tensor: id=8726, shape=(3,), dtype=int32, numpy=array([0, 1, 0], dtype=int32)>), ('parch', <tf.Tensor: id=8727, shape=(3,), dtype=int32, numpy=array([0, 2, 0], dtype=int32)>), ('fare', <tf.Tensor: id=8725, shape=(3,), dtype=float32, numpy=array([  7.7958, 151.55  ,  13.    ], dtype=float32)>), ('class', <tf.Tensor: id=8722, shape=(3,), dtype=string, numpy=array([b'Third', b'First', b'Second'], dtype=object)>), ('deck', <tf.Tensor: id=8723, shape=(3,), dtype=string, numpy=array([b'unknown', b'C', b'unknown'], dtype=object)>), ('embark_town', <tf.Tensor: id=8724, shape=(3,), dtype=string, numpy=array([b'Southampton', b'Southampton', b'Southampton'], dtype=object)>), ('alone', <tf.Tensor: id=8721, shape=(3,), dtype=string, numpy=

#### 从文本文件构建数据管道

In [61]:
ds5 = tf.data.TextLineDataset(
    filenames = ["/Users/jun_yu/Documents/yujun_repository/Wide & Deep/wide-and-deep-titan_0512/train.csv",
                 "/Users/jun_yu/Documents/yujun_repository/Wide & Deep/wide-and-deep-titan_0512/eval.csv"],
    ).skip(1)  #略去第一行header

for line in ds5.take(5):
    print(line)

tf.Tensor(b'0,male,22.0,1,0,7.25,Third,unknown,Southampton,n', shape=(), dtype=string)
tf.Tensor(b'1,female,38.0,1,0,71.2833,First,C,Cherbourg,n', shape=(), dtype=string)
tf.Tensor(b'1,female,26.0,0,0,7.925,Third,unknown,Southampton,y', shape=(), dtype=string)
tf.Tensor(b'1,female,35.0,1,0,53.1,First,C,Southampton,n', shape=(), dtype=string)
tf.Tensor(b'0,male,28.0,0,0,8.4583,Third,unknown,Queenstown,y', shape=(), dtype=string)


#### 从文件路径构建数据管道

In [62]:
# ds6 = tf.data.Dataset.list_files("./data/cifar2/train/*/*.jpg")
# for file in ds6.take(5):
#     print(file)

Dataset包含了非常丰富的数据转换功能。

* map: 将转换函数映射到数据集每一个元素。

* flat_map: 将转换函数映射到数据集的每一个元素，并将嵌套的Dataset压平。

* interleave: 效果类似flat_map,但可以将不同来源的数据夹在一起。

* filter: 过滤掉某些元素。

* zip: 将两个长度相同的Dataset横向铰合。

* concatenate: 将两个Dataset纵向连接。

* reduce: 执行归并操作。

* batch : 构建批次，每次放一个批次。比原始数据增加一个维度。 其逆操作为unbatch。

* padded_batch: 构建批次，类似batch, 但可以填充到相同的形状。

* window :构建滑动窗口，返回Dataset of Dataset.

* shuffle: 数据顺序洗牌。

* repeat: 重复数据若干次，不带参数时，重复无数次。

* shard: 采样，从某个位置开始隔固定距离采样一个元素。

* take: 采样，从开始位置取前几个元素。

In [171]:
#map:将转换函数映射到数据集每一个元素

ds = tf.data.Dataset.from_tensor_slices(["hello world","hello China","hello Beijing"])
ds_map = ds.map(lambda x:tf.strings.split(x," "))
for x in ds_map:
    print(list(x.numpy()))

tmp = []
for x in ds:
    tmp.append(x.numpy().decode('utf-8'))
    print(x.numpy().decode('utf-8'))
tmp

[b'hello', b'world']
[b'hello', b'China']
[b'hello', b'Beijing']
hello world
hello China
hello Beijing


['hello world', 'hello China', 'hello Beijing']

In [173]:
#flat_map:将转换函数映射到数据集的每一个元素，并将嵌套的Dataset压平。

ds = tf.data.Dataset.from_tensor_slices(["hello world","hello China","hello Beijing"])
ds_flatmap = ds.flat_map(lambda x:tf.data.Dataset.from_tensor_slices(tf.strings.split(x," ")))
for x in ds_flatmap:
    print(x.numpy().decode('utf-8'))

hello
world
hello
China
hello
Beijing


In [174]:
# interleave: 效果类似flat_map,但可以将不同来源的数据夹在一起。

ds = tf.data.Dataset.from_tensor_slices(["hello world","hello China","hello Beijing"])
ds_interleave = ds.interleave(lambda x:tf.data.Dataset.from_tensor_slices(tf.strings.split(x," ")))
for x in ds_interleave:
    print(x.numpy().decode('utf-8'))

hello
hello
hello
world
China
Beijing


In [175]:
#filter:过滤掉某些元素。

ds = tf.data.Dataset.from_tensor_slices(["hello world","hello China","hello Beijing"])
#找出含有字母a或B的元素
ds_filter = ds.filter(lambda x: tf.strings.regex_full_match(x, ".*[a|B].*"))
for x in ds_filter:
    print(x.numpy().decode('utf-8'))

hello China
hello Beijing


In [176]:
#zip:将两个长度相同的Dataset横向铰合。

ds1 = tf.data.Dataset.range(0,3)
ds2 = tf.data.Dataset.range(3,6)
ds3 = tf.data.Dataset.range(6,9)
ds_zip = tf.data.Dataset.zip((ds1,ds2,ds3))
for x,y,z in ds_zip:
    print(x.numpy(),y.numpy(),z.numpy())

0 3 6
1 4 7
2 5 8


In [178]:
#condatenate:将两个Dataset纵向连接。

ds1 = tf.data.Dataset.range(0,3)
ds2 = tf.data.Dataset.range(3,6)
ds_concat = tf.data.Dataset.concatenate(ds1,ds2)
for x in ds_concat:
    print(x.numpy())

0
1
2
3
4
5


In [189]:
#reduce:执行归并操作。

ds = tf.data.Dataset.from_tensor_slices([1,2,3,4,5.0])
result = ds.reduce(0.0, lambda x,y: tf.add(x,y))    ### 0.0 表示初始值 
print(result.numpy())
result

15.0


<tf.Tensor: id=8395, shape=(), dtype=float32, numpy=15.0>

In [127]:
#batch:构建批次，每次放一个批次。比原始数据增加一个维度。 其逆操作为unbatch。 

ds = tf.data.Dataset.range(20)
ds_batch = ds.batch(5)
for x in ds_batch:
    print(x.numpy())

[0 1 2 3 4]
[5 6 7 8 9]
[10 11 12 13 14]
[15 16 17 18 19]


In [132]:
#padded_batch:构建批次，类似batch, 但可以填充到相同的形状。
elements = [[1, 2],[3, 4, 5],[6, 7],[8]]
ds = tf.data.Dataset.from_generator(lambda: iter(elements), tf.int32) 

ds_padded_batch = ds.padded_batch(2,padded_shapes = [4,])
for x in ds_padded_batch:
#     print(x.numpy())
    print(x)

tf.Tensor(
[[1 2 0 0]
 [3 4 5 0]], shape=(2, 4), dtype=int32)
tf.Tensor(
[[6 7 0 0]
 [8 0 0 0]], shape=(2, 4), dtype=int32)


In [152]:
#window:构建滑动窗口，返回Dataset of Dataset.

ds = tf.data.Dataset.range(12)
#window返回的是Dataset of Dataset,可以用flat_map压平
ds_window = ds.window(3, shift=3).flat_map(lambda x: x.batch(3,drop_remainder=True)) 
for x in ds_window:
    print(x.numpy())
    print(x.shape)

[0 1 2]
(3,)
[3 4 5]
(3,)
[6 7 8]
(3,)
[ 9 10 11]
(3,)


In [121]:
#shuffle:数据顺序洗牌。
ds = tf.data.Dataset.range(7)
ds_shuffle = ds.shuffle(buffer_size = 3)
for x in ds_shuffle:
    print(x.numpy())

2
1
3
5
4
6
0


In [122]:
#repeat:重复数据若干次，不带参数时，重复无数次。
ds = tf.data.Dataset.range(3)
ds_repeat = ds.repeat(2)
for x in ds_repeat:
    print(x.numpy())

0
1
2
0
1
2


In [123]:
#shard:采样，从某个位置开始隔固定距离采样一个元素。
ds = tf.data.Dataset.range(12)
ds_shard = ds.shard(3,index = 1)
for x in ds_shard:
    print(x.numpy())

1
4
7
10


In [125]:
#take:采样，从开始位置取前几个元素。
ds = tf.data.Dataset.range(12)
ds_take = ds.take(3)
# list(ds_take.())

以下是一些构建高效数据管道的建议。

* 1，使用 prefetch 方法让数据准备和参数迭代两个过程相互并行。

* 2，使用 interleave 方法可以让数据读取过程多进程执行,并将不同来源数据夹在一起。

* 3，使用 map 时设置num_parallel_calls 让数据转换过程多进程执行。

* 4，使用 cache 方法让数据在第一个epoch后缓存到内存中，仅限于数据集不大情形。

* 5，使用 map转换时，先batch, 然后采用向量化的转换方法对每个batch进行转换。

#### 使用 cache 方法让数据在第一个epoch后缓存到内存中，仅限于数据集不大情形。

In [78]:
import time

# 模拟数据准备
def generator():
    for i in range(5):
        #假设每次准备数据需要2s
        time.sleep(2) 
        yield i 
ds = tf.data.Dataset.from_generator(generator,output_types = (tf.int32))

In [81]:
# 模拟参数迭代
def train_step():
    #假设每一步训练需要0s
    pass

# 训练过程预计耗时 (5*2+5*0)*3 = 30s
tf.print(tf.constant("start training..."))
for epoch in tf.range(3):
    for x in ds:
        train_step()  
    tf.print("epoch =",epoch," ended")

tf.print(tf.constant("end training..."))

start training...
epoch = 0  ended
epoch = 1  ended
epoch = 2  ended
end training...


In [105]:
#打印时间分割线
@tf.function
def printbar():
    ts = tf.timestamp()
    today_ts = ts%(24*60*60)

    hour = tf.cast(today_ts//3600+8,tf.int32)%tf.constant(24)
    minite = tf.cast((today_ts%3600)//60,tf.int32)
    second = tf.cast(tf.floor(today_ts%60),tf.int32)
    
    def timeformat(m):
        if tf.strings.length(tf.strings.format("{}",m))==1:
            return(tf.strings.format("0{}",m))
        else:
            return(tf.strings.format("{}",m))
    
    timestring = tf.strings.join([timeformat(hour),
                                  timeformat(minite), 
                                  timeformat(second)],separator = ":")
    tf.print("=========="*8,end = "")
    tf.print(timestring)

In [106]:
printbar()

================================================================================19:39:12


#### 使用 interleave 方法可以让数据读取过程多进程执行,并将不同来源数据夹在一起。

In [83]:
file_path ="/Volumes/TOSHIBA/rank_model/no_interest_feature/*.csv"

In [99]:
ds_files = tf.data.Dataset.list_files(file_path)
ds = ds_files.interleave(lambda x:tf.data.TextLineDataset(x).skip(1))

tp = list()
for line in ds.take(3):
    x = list(line.numpy())
    tp.append(x)
#     print(tf.print(line))

#### 使用 map转换时，先batch, 然后采用向量化的转换方法对每个batch进行转换。 

#### 先map后batch

In [76]:
ds = tf.data.Dataset.range(100000)
ds_map_batch = ds.map(lambda x:x**2).batch(20)

In [77]:
for i in ds_map_batch.take(5):
    print(tf.print(i))

[0 1 4 ... 289 324 361]
None
[400 441 484 ... 1369 1444 1521]
None
[1600 1681 1764 ... 3249 3364 3481]
None
[3600 3721 3844 ... 5929 6084 6241]
None
[6400 6561 6724 ... 9409 9604 9801]
None


#### 先batch后map

In [63]:
ds = tf.data.Dataset.range(100000)
ds_batch_map = ds.batch(20).map(lambda x:x**2)

In [74]:
for i in ds_batch_map.take(5):
    print(tf.print(i))

[0 1 4 ... 289 324 361]
None
[400 441 484 ... 1369 1444 1521]
None
[1600 1681 1764 ... 3249 3364 3481]
None
[3600 3721 3844 ... 5929 6084 6241]
None
[6400 6561 6724 ... 9409 9604 9801]
None


In [71]:
tf.print(tf.constant("end vector transformation..."))

end vector transformation...


### Load data using tf.data.Dataset

In [235]:
import pandas as pd
import tensorflow as tf

In [236]:
csv_file = tf.keras.utils.get_file('heart.csv', 'https://storage.googleapis.com/applied-dl/heart.csv')

In [237]:
csv_file

'/Users/jun_yu/.keras/datasets/heart.csv'

In [238]:
df = pd.read_csv(csv_file)

In [239]:
df.shape 

(303, 14)

In [240]:
df.head(3)

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  slope  \
0   63    1   1       145   233    1        2      150      0      2.3      3   
1   67    1   4       160   286    0        2      108      1      1.5      2   
2   67    1   4       120   229    0        2      129      1      2.6      2   

   ca        thal  target  
0   0       fixed       0  
1   3      normal       1  
2   2  reversible       0

In [241]:
df['target'].value_counts()

0    220
1     83
Name: target, dtype: int64

In [242]:
df.dtypes

age           int64
sex           int64
cp            int64
trestbps      int64
chol          int64
fbs           int64
restecg       int64
thalach       int64
exang         int64
oldpeak     float64
slope         int64
ca            int64
thal         object
target        int64
dtype: object

In [243]:
df['thal'] = pd.Categorical(df['thal'])

In [245]:
df['thal'].value_counts()

normal        168
reversible    115
fixed          18
2               1
1               1
Name: thal, dtype: int64

In [248]:
df.thal.cat.codes.value_counts()

3    168
4    115
2     18
1      1
0      1
dtype: int64

In [250]:
df['thal'] = pd.Categorical(df['thal'])
df['thal'] = df.thal.cat.codes

In [251]:
df.head()

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  slope  \
0   63    1   1       145   233    1        2      150      0      2.3      3   
1   67    1   4       160   286    0        2      108      1      1.5      2   
2   67    1   4       120   229    0        2      129      1      2.6      2   
3   37    1   3       130   250    0        0      187      0      3.5      3   
4   41    0   2       130   204    0        2      172      0      1.4      1   

   ca  thal  target  
0   0     2       0  
1   3     3       1  
2   2     4       0  
3   0     3       0  
4   0     3       0

In [252]:
df['thal'].value_counts()

3    168
4    115
2     18
1      1
0      1
Name: thal, dtype: int64

In [253]:
target = df.pop('target')

In [257]:
df.values

array([[63.,  1.,  1., ...,  3.,  0.,  2.],
       [67.,  1.,  4., ...,  2.,  3.,  3.],
       [67.,  1.,  4., ...,  2.,  2.,  4.],
       ...,
       [65.,  1.,  4., ...,  2.,  1.,  4.],
       [48.,  1.,  4., ...,  1.,  2.,  4.],
       [63.,  0.,  4., ...,  2.,  3.,  4.]])

In [258]:
target.values

array([0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0,
       0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1,
       1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1,
       1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1,
       0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0,
       0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1,

In [259]:
df.columns

Index(['age', 'sex', 'cp', 'trestbps', 'chol', 'fbs', 'restecg', 'thalach',
       'exang', 'oldpeak', 'slope', 'ca', 'thal'],
      dtype='object')

In [208]:
dataset = tf.data.Dataset.from_tensor_slices((df.values, target.values))

In [263]:
for feat, targ in dataset.take(5):
    print('Features: {}, Target: {}'.format(feat, targ))

Features: [ 63.    1.    1.  145.  233.    1.    2.  150.    0.    2.3   3.    0.
   2. ], Target: 0
Features: [ 67.    1.    4.  160.  286.    0.    2.  108.    1.    1.5   2.    3.
   3. ], Target: 1
Features: [ 67.    1.    4.  120.  229.    0.    2.  129.    1.    2.6   2.    2.
   4. ], Target: 0
Features: [ 37.    1.    3.  130.  250.    0.    0.  187.    0.    3.5   3.    0.
   3. ], Target: 0
Features: [ 41.    0.    2.  130.  204.    0.    2.  172.    0.    1.4   1.    0.
   3. ], Target: 0


In [264]:
tf.constant(df['thal'])

<tf.Tensor: id=25380, shape=(303,), dtype=int32, numpy=
array([2, 3, 4, 3, 3, 3, 3, 3, 4, 4, 2, 3, 2, 4, 4, 3, 4, 3, 3, 3, 3, 3,
       3, 4, 4, 3, 3, 3, 3, 4, 3, 4, 3, 4, 3, 3, 4, 2, 4, 3, 4, 3, 4, 4,
       2, 3, 3, 4, 3, 3, 4, 3, 3, 3, 4, 3, 3, 3, 3, 3, 3, 4, 4, 3, 3, 4,
       4, 2, 3, 3, 4, 3, 4, 3, 3, 4, 4, 3, 3, 4, 4, 3, 3, 3, 3, 4, 4, 4,
       3, 3, 4, 3, 4, 4, 3, 4, 3, 3, 3, 4, 3, 4, 4, 3, 3, 4, 4, 4, 4, 4,
       3, 3, 3, 3, 4, 3, 4, 3, 4, 4, 3, 3, 2, 4, 4, 2, 3, 3, 4, 4, 3, 4,
       3, 3, 4, 2, 4, 4, 3, 4, 3, 3, 3, 3, 3, 3, 3, 3, 3, 4, 4, 4, 4, 4,
       4, 3, 3, 3, 4, 3, 4, 3, 4, 3, 3, 3, 3, 3, 3, 3, 4, 3, 3, 3, 3, 3,
       3, 3, 3, 3, 3, 3, 3, 4, 4, 3, 3, 3, 3, 3, 3, 3, 3, 4, 3, 4, 3, 2,
       4, 4, 3, 3, 3, 3, 3, 3, 4, 3, 3, 3, 3, 3, 2, 2, 4, 3, 4, 2, 4, 3,
       3, 4, 3, 3, 3, 3, 4, 3, 4, 3, 4, 2, 2, 4, 3, 4, 3, 2, 4, 3, 3, 2,
       4, 4, 4, 4, 3, 0, 3, 3, 3, 3, 1, 4, 3, 3, 3, 4, 3, 4, 3, 3, 3, 4,
       3, 3, 4, 4, 4, 4, 3, 3, 4, 3, 4, 3, 4, 4, 3, 4, 4, 3, 4, 4, 3

In [211]:
train_dataset = dataset.shuffle(len(df)).batch(1)

In [212]:
def get_compiled_model():
    model = tf.keras.Sequential([
    tf.keras.layers.Dense(10, activation='relu'),
    tf.keras.layers.Dense(10, activation='relu'),
    tf.keras.layers.Dense(1)])
    
    model.compile(optimizer='adam',
                  loss=tf.keras.losses.BinaryCrossentropy(from_logits=True),
                  metrics=['accuracy'])
    return model

In [213]:
model = get_compiled_model()
model.fit(train_dataset, epochs=15)

W0513 17:34:40.191283 140737132438464 base_layer.py:1814] Layer sequential is casting an input tensor from dtype float64 to the layer's dtype of float32, which is new behavior in TensorFlow 2.  The layer has dtype float32 because it's dtype defaults to floatx.

If you intended to run this layer in float32, you can safely ignore this warning. If in doubt, this warning is likely only an issue if you are porting a TensorFlow 1.X model to TensorFlow 2.

To change all layers to have dtype float64 by default, call `tf.keras.backend.set_floatx('float64')`. To change just this layer, pass dtype='float64' to the layer constructor. If you are the author of this layer, you can disable autocasting by passing autocast=False to the base Layer constructor.



Epoch 1/15
303/303 [==============================] - 6s 20ms/step - loss: 0.7392 - accuracy: 0.7426
Epoch 2/15
303/303 [==============================] - 1s 2ms/step - loss: 0.6225 - accuracy: 0.7327
Epoch 3/15
303/303 [==============================] - 1s 2ms/step - loss: 0.6001 - accuracy: 0.7228
Epoch 4/15
303/303 [==============================] - 1s 2ms/step - loss: 0.5833 - accuracy: 0.7162
Epoch 5/15
303/303 [==============================] - 1s 2ms/step - loss: 0.5605 - accuracy: 0.7393
Epoch 6/15
303/303 [==============================] - 1s 2ms/step - loss: 0.5232 - accuracy: 0.7360
Epoch 7/15
303/303 [==============================] - 1s 2ms/step - loss: 0.5228 - accuracy: 0.7459
Epoch 8/15
303/303 [==============================] - 1s 2ms/step - loss: 0.5139 - accuracy: 0.7228
Epoch 9/15
303/303 [==============================] - 1s 2ms/step - loss: 0.5105 - accuracy: 0.7228
Epoch 10/15
303/303 [==============================] - 1s 2ms/step - loss: 0.5098 - accuracy: 0.732

In [214]:
inputs = {key: tf.keras.layers.Input(shape=(), name=key) for key in df.keys()}

x = tf.stack(list(inputs.values()), axis=-1)

x = tf.keras.layers.Dense(10, activation='relu')(x)
output = tf.keras.layers.Dense(1)(x)

model_func = tf.keras.Model(inputs=inputs, 
                            outputs=output)

model_func.compile(optimizer='adam',
                   loss=tf.keras.losses.BinaryCrossentropy(from_logits=True),
                   metrics=['accuracy'])

In [215]:
dict_slices = tf.data.Dataset.from_tensor_slices((df.to_dict('list'), target.values)).batch(16)

In [229]:
for dict_slice in dict_slices.take(1):
    print(type(dict_slice))
    print(dict_slice[0].values())

<class 'tuple'>
dict_values([<tf.Tensor: id=25332, shape=(16,), dtype=int32, numpy=
array([63, 67, 67, 37, 41, 56, 62, 57, 63, 53, 57, 56, 56, 44, 52, 57],
      dtype=int32)>, <tf.Tensor: id=25340, shape=(16,), dtype=int32, numpy=array([1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1], dtype=int32)>, <tf.Tensor: id=25335, shape=(16,), dtype=int32, numpy=array([1, 4, 4, 3, 2, 2, 4, 4, 4, 4, 4, 2, 3, 2, 3, 3], dtype=int32)>, <tf.Tensor: id=25344, shape=(16,), dtype=int32, numpy=
array([145, 160, 120, 130, 130, 120, 140, 120, 130, 140, 140, 140, 130,
       120, 172, 150], dtype=int32)>, <tf.Tensor: id=25334, shape=(16,), dtype=int32, numpy=
array([233, 286, 229, 250, 204, 236, 268, 354, 254, 203, 192, 294, 256,
       263, 199, 168], dtype=int32)>, <tf.Tensor: id=25337, shape=(16,), dtype=int32, numpy=array([1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0], dtype=int32)>, <tf.Tensor: id=25339, shape=(16,), dtype=int32, numpy=array([2, 2, 2, 0, 2, 0, 2, 0, 2, 2, 0, 2, 2, 0, 0, 0], dtype=in

In [218]:
model_func.fit(dict_slices, epochs=15)

Epoch 1/15
19/19 [==============================] - 1s 51ms/step - loss: 3.4952 - accuracy: 0.7426
Epoch 2/15
19/19 [==============================] - 0s 6ms/step - loss: 2.9554 - accuracy: 0.7228
Epoch 3/15
19/19 [==============================] - 0s 6ms/step - loss: 2.5521 - accuracy: 0.7459
Epoch 4/15
19/19 [==============================] - 0s 5ms/step - loss: 2.3603 - accuracy: 0.7327
Epoch 5/15
19/19 [==============================] - 0s 5ms/step - loss: 2.1574 - accuracy: 0.7393
Epoch 6/15
19/19 [==============================] - 0s 5ms/step - loss: 2.0183 - accuracy: 0.7327
Epoch 7/15
19/19 [==============================] - 0s 5ms/step - loss: 1.9161 - accuracy: 0.7195
Epoch 8/15
19/19 [==============================] - 0s 4ms/step - loss: 1.8166 - accuracy: 0.7228
Epoch 9/15
19/19 [==============================] - 0s 5ms/step - loss: 1.7166 - accuracy: 0.7162
Epoch 10/15
19/19 [==============================] - 0s 5ms/step - loss: 1.6302 - accuracy: 0.7162
Epoch 11/15
19/19 